Models/ErrorViewModel.cs
using System;

namespace CalculatorWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CalcController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CSharp.RuntimeBinder;
using System;


namespace CalculatorWeb.Controllers
{

    public class CalcController : Controller
    {
        [HttpGet]
        public ActionResult Add()
        {
            return View();

        }

        [HttpPost]
        public ActionResult Add(string firstNumber, string secondNumber)
        {
          
            GetBiggerSquare(firstNumber, secondNumber);
            return View();
        }

        private String GetBiggerSquare(string firstNumber, string secondNumber)
        {
            bool intResultTryParseOne = false;
            bool intResultTryParseTwo = false;
            int numberOne;
            int numberTwo;
            String text = null;
            intResultTryParseOne = int.TryParse(firstNumber, out numberOne);
            intResultTryParseTwo = int.TryParse(secondNumber, out numberTwo);
            
            if (intResultTryParseOne == false || intResultTryParseTwo == false)
            {
                text = "ERROR!... ONLY NUMBERS ARE EXPECTED";
            }

            else if (intResultTryParseOne == true && intResultTryParseTwo)
            {
                double numberOneSquare = Math.Sqrt(numberOne);
                double numberTwoSquare = Math.Sqrt(numberTwo);
                if (numberOne < 0 || numberTwo < 0)
                {
                    text = "Number Cannot be negative, enter another value";
                }
                else if (numberOneSquare == numberTwoSquare)
                {
                    text = "The square root are same, enter another value";
                }
                else if (numberOneSquare > numberTwoSquare)
                {
                    text = "The number " + numberOne + " with Square root " + numberOneSquare + " has a higher square root than the number " + numberTwo + " with square root " + numberTwoSquare;
                   
                   
                }
                else
                {
                    text = "The number " + numberTwo + " with Square root " + numberTwoSquare + " has a higher square root than the number " + numberOne + " with square root " + numberOneSquare;
                }

            }
            ViewBag.Result = text;
            return ViewBag.Result;
        }

    }

}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CalculatorWeb.Models;

namespace CalculatorWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Calc/Add.cshtml
@{
    ViewData["Title"] = "Addition Page";
}

<div class="text-center">
    <h1 class="display-4"> The Additon Calculator</h1>
</div>

@{
    if(@ViewBag.Result != null)
        { 
            <div>
                <p> @ViewBag.Result</p>
            </div>
        }
    }


<div>

    <form asp-controller="Calc" asp-action="Add" method="POST">
        <input type="text" placeholder="Enter first number" name="firstNumber"/>
        <input type="text" placeholder="Enter second number"  name="secondNumber"/>
        <button type="submit">Submit</button>
    </form>
    
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CalculatorWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CalculatorWeb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CalculatorWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>